import { groupBySeverity, topRules } from "../compliance.js";
import type { SecurityFinding } from "../findings.js";
import type { ReportMeta } from "./json.js";

export function renderPrDescription(
  findings: SecurityFinding[],
  meta: ReportMeta,
  options: { includeAutoFixChecklist?: boolean } = {},
): string {
  const includeAutoFixChecklist = options.includeAutoFixChecklist ?? true;
  const lines: string[] = [];
  lines.push("## Security remediation");
  lines.push("");
  lines.push(
    `Automated security scan of \`${meta.repoRoot}\` found **${findings.length}** issue(s).`,
  );
  lines.push("");
  const bySev = groupBySeverity(findings);
  lines.push("| Severity | Count |");
  lines.push("|---|---:|");
  for (const sev of ["critical", "high", "medium", "low", "info"] as const) {
    lines.push(`| ${sev} | ${bySev[sev] ?? 0} |`);
  }
  lines.push("");
  const top = topRules(findings, 10);
  if (top.length > 0) {
    lines.push("### Top findings");
    lines.push("");
    for (const r of top) {
      lines.push(`- \`${r.ruleId}\` — ${r.count} hit(s)`);
    }
    lines.push("");
  }
  if (includeAutoFixChecklist) {
    lines.push("### Fix checklist");
    lines.push("");
    lines.push("- [ ] Review and triage the top 10 findings");
    lines.push("- [ ] Apply high/critical fixes first");
    lines.push("- [ ] Re-run the security scan and confirm zero regressions");
    lines.push("- [ ] Update tests as needed");
    lines.push("");
  }
  lines.push("---");
  lines.push(
    `Generated by security-mcp-server @ ${meta.finishedAt}. ` +
      `Scanners: ${Object.entries(meta.scannerVersions)
        .map(([k, v]) => `${k}@${v ?? "?"}`)
        .join(", ")}.`,
  );
  return lines.join("\n");
}
